version: '3'
services:
  api:
    build: .
    ports:
      - 4000:4000
    environment:
      - PG_HOST=db
      - REDIS_HOST=redis
    depends_on:
      - db
      - redis
    command: bash -c "yarn tsc && yarn migrate && yarn serve"
  db:
    image: postgres:13
    environment:
      - PORT=4000
      - JWT_SECRET="tifo"
      - PG_USERNAME="postgres"
      - PG_PASSWORD=${PG_PASSWORD}
      - PG_HOST="localhost"
      - PG_PORT="5432"
      - PG_DB="test"
      - WOO_CLIENT_KEY=${WOO_CLIENT_KEY}
      - WOO_CLIENT_SECRET=${WOO_CLIENT_SECRET}
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
  redis:
    image: redis:6
